<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/06/22 18:14:51

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=vota',
  'username' => 'vota',
  'password' => 'inteligente',
  'name' => 'doctrine',
)),);
