generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Partido
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          partido
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:   Gestión de Partidos
        display: [=nombre, sigla]
        sort:    [nombre, asc]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
